apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: absuite-db-pvc
  namespace: absuite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
